
coverage:
  precision: 2
  round: nearest
  range: "60...90"
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        target: 80%


codecov:
  branch: master

comment:
  layout: "diff"

coverage:
  ignore: 
    - "test"  # ignore folders and all its contents
    - "src/main.cpp"  # ignore single files
