StateMachine: AbstractState Class Reference
AbstractState Class Reference abstract
#include <States.h>
Public Member Functions
virtual void sell (Machine &machine, int quantity)=0
virtual void refill (Machine &machine, int quantity)=0
virtual ~AbstractState ()
Protected Member Functions
void setState (Machine &machine, AbstractState *st)
void updateStock (Machine &machine, int quantity)
Constructor & Destructor Documentation
AbstractState::~AbstractState () virtual
Member Function Documentation
virtual void AbstractState::refill (Machine & machine, int quantity) pure virtual
Implemented in SoldOut, and Normal.
Referenced by Machine::refill().
virtual void AbstractState::sell (Machine & machine, int quantity) pure virtual
Implemented in SoldOut, and Normal.
Referenced by Machine::sell().
void AbstractState::setState (Machine & machine, AbstractState * st) protected
References Machine::mState.
Referenced by SoldOut::refill(), and Normal::sell().
void AbstractState::updateStock (Machine & machine, int quantity) protected
References Machine::mStockQuantity.
Referenced by Normal::refill(), SoldOut::refill(), and Normal::sell().
The documentation for this class was generated from the following files:
/home/johan/Workspace/Code/State Machine/include/States.h
/home/johan/Workspace/Code/State Machine/src/States/AbstractState.cpp