StateMachine: Machine Class Reference
Machine Class Reference
#include <Machine.h>
Public Member Functions
Machine (int inStockQuantity)
void sell (int quantity)
void refill (int quantity)
int getCurrentStock ()
~Machine ()
Private Attributes
int mStockQuantity
AbstractState * mState
Friends
class AbstractState
Constructor & Destructor Documentation
Machine::Machine (int inStockQuantity)
Machine::~Machine ()
References mState.
Member Function Documentation
int Machine::getCurrentStock ()
References mStockQuantity.
Referenced by main(), Normal::refill(), and Normal::sell().
void Machine::refill (int quantity)
References mState, and AbstractState::refill().
Referenced by main().
void Machine::sell (int quantity)
References mState, and AbstractState::sell().
Referenced by main().
Friends And Related Function Documentation
friend class AbstractState friend
Member Data Documentation
AbstractState* Machine::mState private
Referenced by refill(), sell(), AbstractState::setState(), and ~Machine().
int Machine::mStockQuantity private
Referenced by getCurrentStock(), and AbstractState::updateStock().
The documentation for this class was generated from the following files:
/home/johan/Workspace/Code/State Machine/include/Machine.h
/home/johan/Workspace/Code/State Machine/src/Machine.cpp